### ISSUE TITLE
Preparing 5-Node Kubernetes Cluster

### ISSUE THREAD

**Issue by ashutoshbhakare** [collabnix/kubelabs#139]
What does this script do?
The first line kubeadm init initializes a Kubernetes control-plane node and execute the below phases: 
If also add a CNI plugin called kube-router using kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 

The above line may be added to give the learner clarity on the same

**Comment by collabnix** [comment]
@ashutoshbhakare Do you want to add the comments to the bootstrap.sh script. Go ahead and raise PR.

**Comment by ajeetraina** [comment]
Closing this issue as the description is already added.
