### ISSUE TITLE
k8s installation in ubuntu

### ISSUE THREAD

**Issue by gauravrattan** [collabnix/kubelabs#160]
Container Runtime is not installed.
link: https://github.com/collabnix/kubelabs/blob/master/install/ubuntu/README.md

**Comment by gauravrattan** [comment]
@ajeetraina can i work on this?

**Comment by ajeetraina** [comment]
Yes @gauravrattan You're most welcome.
Also, are you a part of Collabnix Slack https://launchpass.com/collabnix?

**Comment by gauravrattan** [comment]
Yes I am part of Slack channel.
