### ISSUE TITLE
Kubelabs 101 "Deep dive into Kubernetes Architecture" link broken

### ISSUE THREAD

**Issue by mkrupczak3** [collabnix/kubelabs#2]
On [this](https://github.com/collabnix/kubelabs/blob/master/kubernetes/workshop/README.md) page, it appears that the link [Deep Dive into Kubernetes Architecture](https://github.com/collabnix/kubelabs/blob/master/kubernetes/workshop/Kubernetes_Architecture.md) is broken. 

Is this document missing or is the link broken perchance?

**Comment by collabnix** [comment]
@mkrupczak3  Please refer https://github.com/collabnix/dockerlabs/kubernetes for labs as of now. We are migrating the labs from dockerlabs to kubelabs.

**Comment by mkrupczak3** [comment]
Ah, thanks.
Cheers
