### ISSUE TITLE
Fix case insensitive filename collisions on mac os filesystem

### ISSUE THREAD

**Issue by akshitgrover** [collabnix/kubelabs#35]

**Comment by akshitgrover** [comment]
Mac Os treats
Network_Policies101/Deny_ingress_traffic_that_has_no_rules.md
Network_Policies101/deny_ingress_traffic_that_has_no_rules.md
As same file, To avoid losing content we need to rename these files.

**Comment by sangam14** [comment]
Let's rename :blush:
