### ISSUE TITLE
Issue while Creating First Deployment

### ISSUE THREAD

**Issue by ErKiran** [collabnix/kubelabs#59]
When running the command from this page 
https://collabnix.github.io/kubelabs/Deployment101/

I get the following error 
`error: unable to recognize "nginx-dep.yaml": no matches for kind "Deployment" in version "apps/v1beta2"`

The same issue was also open in dockerlabs 
https://github.com/collabnix/dockerlabs/issues/311

When tried to run this in terminal
```
git clone https://github.com/collabnix/dockerlabs
cd dockerlabs/kubernetes/workshop/Deployment101
kubectl create -f nginx-dep.yaml
deployment.apps/nginx-deployment created

**Comment by collabnix** [comment]
Change apps/v1betas2 to apps/v1 and that would fix the issue. Watch out https://youtu.be/SgMrzvZGVic
