### ISSUE TITLE
Finding Index.html

### ISSUE THREAD

**Issue by PratikLomte** [collabnix/kubelabs#60]
I am completely new person here nut after looking at your website (https://kubelabs.collabnix.com/) , I found a couple of things I can improve. But I am unable to find the source code for the respective webpage i.e index.html. If someone can point that out maybe I can contribute to this project

**Comment by collabnix** [comment]
Cc @sangam14

**Comment by sangam14** [comment]
Default.html under Layout will be the jekyll page which use markdown as index

**Comment by sangam14** [comment]
@PratikLomte let me know if you need any help !
