### ISSUE TITLE
Unable to bootstrap the node cluster.

### ISSUE THREAD

**Issue by Rohan749** [collabnix/kubelabs#71]
While preparing 5 nodes Kubernetes Cluster, after cloning the repository, the given command was not working.
It says -> cannot access 'bootstrap.sh': No such file or directory

To change mode executable for bootstrap.sh, it asks to type the following command:
![Screenshot from 2022-01-18 11-27-36](https://user-images.githubusercontent.com/90546860/149880269-36f1b6ab-e031-4f49-838d-6ce385903d86.png)

After typing the command, the result I got:
![Screenshot from 2022-01-18 11-27-46](https://user-images.githubusercontent.com/90546860/149880290-a42e48fa-570b-4e0c-9e68-8ec941af645f.png)

Please correct me if I misunderstood any step.

**Comment by ajeetraina** [comment]
Hi @Rohan749 You will need to change directory to kubelabs first

```
cd kubelabs
```

and then execute the script.

**Comment by Rohan749** [comment]
Thankyou @ajeetraina !
