### ISSUE TITLE
Create section for Helm101

### ISSUE THREAD

**Issue by Phantom-Intruder** [collabnix/kubelabs#81]
I noticed that there are no tutorials on Helm. Has this been worked on before, and is a section on Helm appropriate here? If so, I can contribute.

**Comment by collabnix** [comment]
@Phantom-Intruder You are most welcome to contribute.

**Comment by Phantom-Intruder** [comment]
#82 PR for this

**Comment by collabnix** [comment]
Thanks. I have merged it. Please add a link at the end of each page so that it becomes easy for readers.

**Comment by collabnix** [comment]
Keep contributing,.

**Comment by Phantom-Intruder** [comment]
Added links and also added parts related to chart hooks, repositories, and chart testing

**Comment by collabnix** [comment]
Thanks @Phantom-Intruder for all your great work.
